<?php

namespace TomatoPHP\FilamentMediaManager\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
class Folder extends Model implements HasMedia
{
    use InteractsWithMedia;
    
    // relazione ai figli immediati
    public function children()
    {
        return $this->hasMany(self::class, 'model_id')
                    ->where('model_type', self::class);
    }

    /** Tutte le discendenti (inclusa la cartella corrente) */
    public function descendantsAndSelf(): EloquentCollection
    {
        // inizi con te stesso
        $all = new EloquentCollection([$this]);

        // prendi i figli immediati
        $children = static::where('model_id', $this->id)
                        ->where('model_type', self::class)
                        ->get();

        // ricorsione
        foreach ($children as $child) {
            $all = $all->merge($child->descendantsAndSelf());
        }

        return $all;
    }
    public function parentFolder()
    {
        return $this->belongsTo(
            self::class,
            'model_id'
        )//->where('model_type', self::class);
        ;
    }

    /** Tutti i media presenti nella cartella e in tutte le sue sottocartelle */
    public function allMedia(): EloquentCollection
    {
        return new EloquentCollection(
            $this->descendantsAndSelf()
                ->flatMap(fn ($folder) => $folder->media)
                ->unique('id')
                ->values()
        );
    }

    protected $fillable = [
        'parent_id',
        'model_type',
        'model_id',
        'name',
        'collection',
        'description',
        'icon',
        'color',
        'is_protected',
        'password',
        'is_hidden',
        'is_favorite',
        'is_public',
        'has_user_access',
        'user_id',
        'user_type',
    ];

    protected $casts = [
        'is_protected' => 'boolean',
        'is_hidden' => 'boolean',
        'is_favorite' => 'boolean',
        'is_public' => 'boolean',
        'has_user_access' => 'boolean'
    ];

    public function model()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->morphTo();
    }

    public function users()
    {
        return $this->morphedByMany(User::class, 'model', 'folder_has_models', 'folder_id', 'model_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

            static::addGlobalScope('user', function ($query) {
                if(filament('filament-media-manager')->allowUserAccess && auth()->check()){
                    $query
                        ->where('user_id', auth()->id())
                        ->orWhere('is_public',false)
                        ->where('has_user_access', true)
                        ->whereHas('users', function ($query) {
                            $query->where('model_id', auth()->id())
                                ->where('model_type', get_class(auth()->user()));
                        })
                        ->orWhere('is_public', true);
                }
            });

    }

    public function folders()
    {
        return $this->hasMany(Folder::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(Folder::class, 'parent_id');
    }
}
